// ── 2. Technology Landscape ──
// [Provide an analysis of the current technology landscape that justifies how the proposed platform technology would accelerate the emergence of new technologies and lines of research. The Technology Landscape Analysis should compare current state-of-the-art technology and should provide a clear description of the team's goal to progress the technology and unlock fundamentally new capabilities. A plot or other figure to quantitatively depict the current technology landscape and desired goal(s) of the NSF X-Lab may be included here.]
#import "../helpers/shared.typ": semibold, Dome, Domes, Dome-Mobile
#import "../helpers/xref.typ": flag
= Technology Landscape <sec-technology-landscape>

The perception–action loop is measured today by six mature but separately-evolved instrument ecosystems, each excellent within its own thread. Body kinematics are captured by markerless pose estimation (DeepLabCut, SLEAP, ViTPose, FreeMoCap), marker-based systems (Vicon, Qualisys, OptiTrack), and inertial suits (Xsens); the forces behind that motion by force plates (AMTI, Bertec), instrumented treadmills, and pressure-sensing insoles; gaze by wearable eye trackers (Pupil Labs, Tobii); neural activity by Neuropixels probes, miniscopes, and mobile EEG; muscle activity by surface and intramuscular EMG; and the surrounding scene by photogrammetry, Gaussian splatting, RGB-D, and LiDAR. Every one of these threads is precise and improving along its own trajectory. Progress within any single channel is not the bottleneck.

The bottleneck is that these instruments do not compose. Each defines its own coordinate frame, runs on its own clock, and names its quantities in its own scheme — so a "gaze point" in one system is not the same measured quantity as in another — and none of them carry the uncertainty of a measurement across a modality boundary. Assembling the whole loop therefore falls on each lab as bespoke, one-off integration. Mobile Brain/Body Imaging is the fifteen-year demonstration of this ceiling: it is a methodology rather than an instrument, because the integration burden it describes is handed anew to every team that adopts it, and its results rarely leave the Methods sections of the labs that built them.

The deeper reason integration never sticks is that today's platforms are organized around sensors rather than around measurements. A tool is built for a particular camera model or force-plate vendor, not for kinematics as such — even though kinematics is kinematics whether it came from cameras or from IMUs — so records from different labs, species, and hardware generations cannot be pooled, compared, or cumulatively improved. #flag(kind: "verbose")[The #Dome inverts this. It is defined by the measurement, carries an unbroken chain of calibration and propagated uncertainty from raw sensor to reconstructed quantity, and therefore yields the same canonical, uncertainty-tagged record regardless of which instruments happen to be present.] // NOTE (verbose, not strictly redundant): this "defined by the measurement, not the sensor" framing echoes Mission's "All Domes produce the same output regardless of the component instruments" (@sec-new-instrument). Likely intentional restatement for a section meant to stand alone, but flagging since the phrasing is near-identical — worth varying the wording or shortening one instance.
This is the capability no existing system provides: not a better sensor in any one thread, but a single instrument in which every thread is spatially calibrated, temporally synchronized, and semantically unified.

Two adjacent fields are stalled for want of exactly this record. Computer-vision pose estimation has drifted away from the pixels toward ungroundable targets — 3D-from-2D, mesh fitting, semantic segmentation — while still benchmarking against COCO imagery scraped from the early 2000s, and it fails on the out-of-distribution movement that matters most: clinical gait, extreme athletics, animal locomotion. It needs physical ground truth at scale, which a calibrated multi-camera #Dome produces by construction. Legged-robot reinforcement learning is likewise limited not by simulation — MuJoCo, Isaac Lab, and Genesis are excellent — but by the sim-to-real gap, and the resource that would close it is uncertainty-tagged, multimodal recordings of real agents in real environments; the standard corpora (Human3.6M, AMASS, GRAB) are single-modality, lab-constrained, or carry no uncertainty at all. The same #Dome record feeds both. Building the instrument that makes the loop itself the unit of measurement is the goal of this proposal.
