// ── 2. Technology Landscape ──
// [Provide an analysis of the current technology landscape that justifies how the proposed platform technology would accelerate the emergence of new technologies and lines of research. The Technology Landscape Analysis should compare current state-of-the-art technology and should provide a clear description of the team's goal to progress the technology and unlock fundamentally new capabilities. A plot or other figure to quantitatively depict the current technology landscape and desired goal(s) of the NSF X-Lab may be included here.]
#import "../helpers/shared.typ": semibold, Dome, Domes, Dome-Mobile
#import "../helpers/xref.typ": flag, suggestion
#import "../helpers/dome-sensor-estimate-model/dome-chain-quantified.typ": dome-chain-quantified-figure
= Technology Landscape <sec-technology-landscape>

The perception–action loop is measured today by six mature but separately-evolved instrument ecosystems, each excellent within its own thread. Body kinematics are captured by markerless pose estimation (DeepLabCut, SLEAP, ViTPose, FreeMoCap), marker-based systems (Vicon, Qualisys, OptiTrack), and inertial suits (Xsens); the forces behind that motion by force plates (AMTI, Bertec), instrumented treadmills, and pressure-sensing insoles; gaze by wearable eye trackers (Pupil Labs, Tobii); neural activity by Neuropixels probes, miniscopes, and mobile EEG; muscle activity by surface and intramuscular EMG; and the surrounding scene by photogrammetry, Gaussian splatting, RGB-D, and LiDAR. Every one of these threads is precise and improving along its own trajectory. Progress within any single channel is not the bottleneck.

#suggestion(note: [§2 figure lead-in + desideratum-error framing — Claude draft; integrate into prose and add a permanent in-text figure reference before submission])[
And no single channel is the quantity we ultimately need. What matters is the error of the *composed desideratum*: for vision, gaze in world coordinates resolved finely enough to predict the neural activity it drives — on the order of a degree. That error is a budget accumulated across the whole measurement chain, and today it is not met. The best mobile eye trackers reach 0.6--1.8° in the head frame (Tobii Pro Glasses 3, Pupil Labs Neon, AdHawk MindLink), but composing gaze into the world through head and body pose and scene geometry, the only published end-to-end eye + IMU + world reconstruction — this team's own prior work — lands at ±1° calibrated and ±2--3° in natural walking (Matthis et al. 2018; Muller et al. 2022/2023), with further unquantified error wherever a closed, proprietary pipeline intervenes (@fig-landscape-quantified). No existing toolchain delivers sub-degree gaze-in-world with a traceable, propagated uncertainty budget — precisely what the #Dome is built to provide.
]

The bottleneck is that these instruments do not compose. Each defines its own coordinate frame, runs on its own clock, and names its quantities in its own scheme — so a "gaze point" in one system is not the same measured quantity as in another — and none of them carry the uncertainty of a measurement across a modality boundary. Assembling the whole loop therefore falls on each lab as bespoke, one-off integration. Mobile Brain/Body Imaging is the fifteen-year demonstration of this ceiling: it is a methodology rather than an instrument, because the integration burden it describes is handed anew to every team that adopts it, and its results rarely leave the Methods sections of the labs that built them.

The deeper reason integration never sticks is that today's platforms are organized around sensors rather than around measurements. A tool is built for a particular camera model or force-plate vendor, not for kinematics as such — even though kinematics is kinematics whether it came from cameras or from IMUs — so records from different labs, species, and hardware generations cannot be pooled, compared, or cumulatively improved. The #Dome inverts this. It is defined by the measurement, carries an unbroken chain of calibration and propagated uncertainty from raw sensor to reconstructed quantity, and therefore yields the same canonical, uncertainty-tagged record regardless of which instruments happen to be present. // NOTE (unflagged 2026-07-13): this "defined by the measurement, not the sensor" line is the PAYOFF of §2's landscape argument and §2 is the tightest section in the proposal — do not tighten it. The near-identical phrasing lives in Mission (@sec-new-instrument, "All Domes produce the same output...") and Outcomes (@sec-instrument). Resolve the three-way echo by trimming the MISSION instance (which is over-long anyway), leaving §2 and §3 as the two legitimate statements (landscape claim vs. delivered outcome).
This is the capability no existing system provides: not a better sensor in any one thread, but a single instrument in which every thread is spatially calibrated, temporally synchronized, and semantically unified.

Two adjacent fields are stalled for want of exactly this record. Computer-vision pose estimation has drifted away from the pixels toward ungroundable targets — 3D-from-2D, mesh fitting, semantic segmentation — while still benchmarking against COCO imagery scraped from the early 2000s, and it fails on the out-of-distribution movement that matters most: clinical gait, extreme athletics, animal locomotion. It needs physical ground truth at scale, which a calibrated multi-camera #Dome produces by construction. Legged-robot reinforcement learning is likewise limited not by simulation — MuJoCo, Isaac Lab, and Genesis are excellent — but by the sim-to-real gap, and the resource that would close it is uncertainty-tagged, multimodal recordings of real agents in real environments; the standard corpora (Human3.6M, AMASS, GRAB) are single-modality, lab-constrained, or carry no uncertainty at all. The same #Dome record feeds both. Building the instrument that makes the loop itself the unit of measurement is the goal of this proposal.

#v(1em)
#dome-chain-quantified-figure
