// ── 2. Technology Landscape ──
// [Provide an analysis of the current technology landscape that justifies how the proposed platform technology would accelerate the emergence of new technologies and lines of research. The Technology Landscape Analysis should compare current state-of-the-art technology and should provide a clear description of the team's goal to progress the technology and unlock fundamentally new capabilities. A plot or other figure to quantitatively depict the current technology landscape and desired goal(s) of the NSF X-Lab may be included here.]
#import "../helpers/shared.typ": semibold, Dome, Domes, Dome-Mobile
#import "../helpers/xref.typ": flag, suggestion
#import "../helpers/dome-sensor-estimate-model/dome-chain-quantified.typ": dome-chain-quantified-figure
= Technology Landscape <sec-technology-landscape>

// NOTE 2026-07-13 (Claude): §2 rewritten to the benchmark→Body/Eye/World structure you sketched,
// aligned with §3's subsections and the milestone table (Body/Eye/World/Variants). Preserves your
// eye/torsion argument and the RL/CV close; adds the World thread; the benchmark now lives here and
// §3's "organizing benchmark" is trimmed to a callback. Prior draft is in git.

The #Dome is organized around a single, demanding measurement target: reconstructing the visual input to a behaving agent's retina precisely enough to predict the neural activity it drives. Concretely, that means estimating gaze-in-world to better than 1° — roughly the diameter of the human fovea — and resolving eye kinematics finely enough to recover retinal optic flow and its derivatives, divergence and curl (@matthis2022; @fig-landscape-quantified). Reaching that target decomposes into three measurement threads, each of which must hit its own precision and then compose into one calibrated record: the *body* that carries the eye, the *eye* itself, and the *world* it looks at. The state of the art, and the gap the #Dome closes, is clearest thread by thread.

*The body.* Body kinematics are captured today by markerless pose estimation (e.g. FreeMoCap, riding a decade of computer-vision advances — OpenPose, DeepLabCut, MediaPipe), marker-based systems (Vicon, Qualisys, OptiTrack), and inertial (IMU) suits (Xsens), with the forces behind that motion measured by force plates (AMTI, Bertec), instrumented treadmills, and pressure insoles. Markerless capture already reaches 2–6° joint-angle accuracy against research-grade references, but in practice most users achive far less accuracy due to errors in camera set up and calibration. 

We target that gap with a *self-calibrating, actuated camera array*  capable of tunings its own extrinsics and intrinsics to optimally cover a selected capture volume, allowing for fluid centralized control and automated AI-self-run experiments on best practices for camera arrangement during motion capture. We use this capacity to validate smaller camera-based capture volumes and create sensor-fused estiamtes that combine triangualted keypoint trajectories with IMU-suit based segment orientation estiamtes to generate *reproducibly* high quality kinematic estimations from any measurement system — both within the lab and out in the world.

*The eye.* Sub-degree gaze-in-world may be reachable with commercial instruments plus FreeMoCap: the best mobile trackers reach 0.6–1.8° in the head frame (Tobii Pro Glasses 3, Pupil Labs Neon, AdHawk MindLink), and the only published end-to-end eye + IMU + world reconstruction — this team's own prior work — composes them to ±1° calibrated and ±2–3° in natural walking (@matthis2018; @muller2023). That much is careful extension of prior art. Retinal *curl*, though, is beyond every available tool, because no eye tracker measures ocular torsion. Vision science has long set torsion aside — defensibly, since it could not be measured and since Listing's Law specifies eye orientation from just two of its three degrees of freedom (elevation and abduction, neglecting torsion). But Listing's Law fails whenever the vestibulo-ocular reflex is active — that is, during essentially all natural behavior — and @matthis2022 implicates retinal curl as a likely control signal for real-world locomotion, a signal the torsional axis directly shapes. Measuring that missing degree of freedom is the design target of our next-generation, dense-sensor-array eye tracker.

*The world.* Reconstructing what lands on the retina requires reconstructing the scene the eye looks at. Scene geometry is captured today by photogrammetry, Gaussian splatting, RGB-D, and LiDAR. The team's own photogrammetry recovers natural terrain to a repeatability near 3 cm — about 0.5° of visual angle. But these scanners are passive and stand outside the agent: none is fused into the moving observer's coordinate frame with propagated uncertainty. We mount the scanner on the agent — a dense-array world-scanner carried on the head — and extend it outdoors on the same drone-swarm nodes that carry the body cameras, so the scene is measured in the same calibrated frame as the body and eye. Inside the flagship, an actuated floor of force, LED, and terrain tiles turns the ground itself into a controllable experimental stimulus (@fig-hero).

*The gap is integration, not any single sensor.* Each thread is excellent and improving on its own, but without an integration they are evolving away from each other. Two adjacent fields are stalled for want of exactly this record. Computer-vision pose estimation has drifted from the pixels toward ungroundable targets — 3D-from-2D, mesh fitting, semantic segmentation — while still benchmarking against COCO imagery scraped from the early 2000s, and it fails on the out-of-distribution movement that matters most: clinical gait, extreme athletics, animal locomotion. It needs physical ground truth at scale, which a calibrated multi-camera #Dome produces by construction. Legged-robot reinforcement learning is limited not by simulation — MuJoCo, Isaac Lab, and Genesis are excellent — but by the sim-to-real gap, and the resource that would close it is uncertainty-tagged, multimodal recordings of real agents in real environments; the standard corpora (Human3.6M, AMASS, GRAB) are single-modality, lab-constrained, or carry no uncertainty at all. The same #Dome record feeds both.

#v(1em)
#dome-chain-quantified-figure
