// // ── 3. Outcomes ──
// [An NSF X-Lab is expected to deliver high-impact, measurable outcomes that advance a nascent platform technology, overcome critical bottlenecks, and realize the team's vision to reshape an entire area of technology or field of scientific research (see Section 7.0 for example outcomes). Phase 0 proposals should describe the team's ambitious target outcomes over a 5- to 7-year timescale to accomplish the stated Mission and the scientific and technical performance benchmarks needed to get there.]
#import "../helpers/xref.typ": collab, suggestion
#import "../helpers/templates/milestones-matrix.typ": milestones-figure
= Outcomes <sec-outcomes>


*The instrument.* Our five-to-seven-year outcome is a single instrument — the DOME — realized in three human-scale forms and an animal-scale form that records the complete perception–action loop as one calibrated, uncertainty-tagged measurement and yields the same canonical record regardless of which sensors are present. DOME-L is the warehouse-scale flagship in Greater Boston; it drives each sub-instrument to its limit and is large enough to physically contain the smaller forms, which makes it the metrological reference for the entire network. DOME-S extends FreeMoCap's webcam capture into the disseminated lab- and classroom-scale form, and DOME-Mobile is the wearable form that carries the measurement onto natural terrain outside the lab. Because the instrument is defined by its measurement ontology rather than by any one sensor, a markerless-camera estimate and an inertial estimate describe the same kinematics and fuse into a single estimate better than either alone.

*The organizing benchmark.* The benchmark that organizes the entire build is veridical retinal input: reconstructing the world projected onto a moving agent's retina to within 1° at the fovea while it fixates a point on the ground at a 45° angle. This target is defensible rather than aspirational because it composes two independently measured error sources — joint-angle accuracy already characterized in FreeMoCap @cherian2026 and the published errors of commercial eye trackers — into one explicit uncertainty budget. Closing that budget is what forces the hardware advances below, so we state the number once and build toward it.

#suggestion(note: [concrete numbers behind the 1° benchmark — frames it as a disciplined tightening of a demonstrated floor, not a leap. Sources: metrics ref §1/§4b; @matthis2018 @muller2023 @cherian2026; refs the quantified figure])[
These error sources are already measured, not hypothetical. FreeMoCap reaches 2–4° sagittal joint-angle RMSE against research-grade optical motion capture on treadmill gait @cherian2026; commercial mobile eye trackers report 0.6–1.8° gaze accuracy in the head frame; and the only published end-to-end fusion of eye, inertial body, and photogrammetric world — this team's own prior work — lands at ±1° under calibration and ±2–3° during natural walking @matthis2018 @muller2023 (@fig-landscape-quantified). The sub-1° veridical-retinal-input target is thus a disciplined tightening of a demonstrated floor, made rigorous by propagating uncertainty end-to-end where prior work stopped at a single-lab estimate.
]

*Body — trustworthy kinematics.* On the motor half of the loop we deliver kinematics clean enough for inverse dynamics from markerless capture. The actuated, self-calibrating camera array places daisy-chained Power-over-Ethernet cameras on programmable mounts that stay metrically calibrated as one instrument while being re-aimed and re-focused from a single console, dissolving the bottleneck that leaves large-volume rigs frozen in place because manual re-calibration is too costly. This is adaptive AI-based sensing in hardware: the algorithm reconfigures the physical optics to maximize observability, running autonomous experiments over camera geometry rather than settling for a hand-placed rig. Success is measured as post-reconfiguration calibration quality and the time from sub-volume selection to calibrated capture, against a fixed-calibration reprojection baseline. Camera-to-IMU fusion then combines noisy-but-accurate outside-in estimates with precise-but-drifting inside-out estimates under explicit per-joint uncertainty, validated as joint-torque uncertainty against force-plate ground truth and muscle-force uncertainty against EMG-informed estimates.

#suggestion(note: [quantified baseline the Body line builds from — concrete cost + accuracy. Source: @cherian2026, metrics ref §2])[
The starting point is already quantified: FreeMoCap recovers joint centers to under 30 mm and sagittal joint angles to 2–4° RMSE against research-grade optical motion capture during treadmill gait, from a roughly \$120 six-webcam rig @cherian2026. The actuated array and camera–IMU fusion target the residual gap to inverse-dynamics-grade kinematics — per-joint uncertainty tight enough that derived joint torques and muscle forces carry meaningful error bars.
]

*Eye — the flagship transducer.* On the sensory half we build the flagship transducer, a binocular eye tracker that measures degrees of freedom commercial trackers omit. It resolves ocular torsion from iris texture — the degree of freedom that corrupts the curl of retinal optic flow and a standing research target @matthis2022 — targets microsaccade-scale resolution, and pursues lens accommodation via dual-Purkinje imaging as a stretch goal. The design bet is a dense multimodal sensor array built like a phone camera bank that trades low profile for data quality, which makes it a camera-quality engineering bet rather than a physics one and keeps unit cost on the commodity-imager curve, so that next-generation eye tracking can saturate the field the way FreeMoCap did for motion capture. Its benchmarks are sub-15-arcminute eye-in-head accuracy, ~1° torsion accuracy, and the composed 1° gaze-in-world target above.

#suggestion(note: [SOTA contrast that sharpens the "measures DoF commercial trackers omit" claim with numbers. Source: metrics ref §1; refs the quantified figure])[
For context, the best shipping mobile trackers report 0.6° (Tobii Pro Glasses 3), ~1° (AdHawk MindLink), and 1.3–1.8° (Pupil Labs Neon) gaze accuracy in the head frame — and none of them measure ocular torsion or lens accommodation at all (@fig-landscape-quantified). The sub-15-arcminute (0.25°) eye-in-head target is finer than any of these, and the torsion and accommodation channels are new measurements rather than incremental ones.
]

*World — the scene the agent acts in.* Reconstructing what the eye sees requires reconstructing the world it acts in, so a head-mounted world-scanner of stereo-RGB, structured-IR, and LiDAR produces per-frame RGB-D and, over longer horizons, a terrain mesh and a SLAM-corrected head trajectory that fixes inertial drift @muller2023. The same scanner package mounts on drone-swarm nodes that act as a mobile extension of the camera array, grounding DOME-Mobile's inside-out estimates outdoors where a fixed rig cannot reach, benchmarked as gaze and kinematic uncertainty against the DOME-L reference during co-recorded trials. Modular floor panels — each a force plate, terrain tile, or LED surface — and the ARGP perturbation platform close the world half of the loop by making the ground itself both sensor and controllable stimulus.

#suggestion(note: [demonstrated world-scan floor the scanner tightens. Source: @muller2023, metrics ref §3/§4b])[
Here too there is a measured baseline: photogrammetric reconstruction of natural terrain from a head-mounted scene camera — again the team's prior work — is repeatable to a median ~3 cm, roughly 0.5° of visual angle, across independent traversals of the same ground @muller2023. The integrated world-scanner tightens and propagates that figure rather than starting from zero.
]

*One record across species.* The measurement crosses species, which is the claim that this reshapes a field rather than sharpening a tool: functionally equivalent instruments at collaborator labs yield the same canonical records as the human instrument. The animal-scale instrument already exists — the team's ferret and mouse builds integrate three-camera gaze, full-body kinematics, and world cameras in one calibrated system, with neural recordings being added now — and the human, mouse, and ferret builds are being brought to functional equivalence, extending to guinea fowl for musculoskeletal biomechanics with EMG #collab("MD") and marmoset for primate electrophysiology #collab("AH")/#collab("JY"). Success is cross-species measurement comparability under shared calibration and data-exchange protocols, so that a reconstructed `RetinalInput` or `RigidBody` denotes the same thing whether it came from a human, a ferret, or a marmoset.

*What the record unlocks.* Because every channel is calibrated, synchronized, and uncertainty-traced within one sensor-grounded ontology, the record yields capabilities that would each otherwise demand a bespoke project. The instrument generates its own training signal by back-projecting calibrated 3D reconstructions onto each camera's 2D view, and the resulting reprojection error fine-tunes pose estimators, measured as improvement on out-of-distribution movement — clinical gait, acrobatics, animal locomotion — rather than on a saturated benchmark: an instrument engineered for next-generation AI training pipelines. The record is natively reinforcement-learning-ready because a DOME export maps directly onto MuJoCo and Isaac Lab rigid-body models with uncertainty intact, so DOME-recorded corpora drive sim-to-real policy transfer and inverse-RL recovery of the control policies underlying observed behavior, testable back in DOME-L via ARGP perturbation.

#suggestion(note: [concrete, already-measured instance of the back-projection self-training unlock — a striking number. Source: @cherian2026 Ch.7 prosthetic study])[
This self-improvement loop is already demonstrated at small scale: a generic pose estimator mistracks a transfemoral prosthesis by up to 152 mm at the ankle, but training a task-specific keypoint model on the instrument's own calibrated data drops that error to 8–14 mm @cherian2026. What was a one-off dissertation result becomes, in the DOME, a standing pipeline that mints ground truth for the movement pose estimators fail on.
]
// NOTE: this is the fuller RigidBody/MuJoCo/Isaac-Lab treatment that Mission's humanoid-robot `RigidBody` example (@sec-new-instrument) is flagged as redundant against — see the red flag there.

*Dissemination and validation.* The outcome is a countable, validated footprint rather than a released codebase: [N] validated DOME-S instances spanning human biomechanics, robotics, visual neuroscience, and clinical sites, each cross-validated against the DOME-L reference and shipped with a build guide, parts list, and calibration protocol any lab can follow. We anchor clinical rigor to FDA 510(k) clearance of the FreeMoCap/DOME instrument for rehabilitation and assessment, letting a regulatory bar drive protocol quality. Phase activities and maturity targets for every line above appear in the Milestone Matrix (@tbl-milestones), whose quantitative exit criteria are the benchmarks named here. [TODO - Are they? Make double sure about that... ]

#v(0.8em)
#milestones-figure