// // ── 3. Outcomes ──
// [An NSF X-Lab is expected to deliver high-impact, measurable outcomes that advance a nascent platform technology, overcome critical bottlenecks, and realize the team's vision to reshape an entire area of technology or field of scientific research (see Section 7.0 for example outcomes). Phase 0 proposals should describe the team's ambitious target outcomes over a 5- to 7-year timescale to accomplish the stated Mission and the scientific and technical performance benchmarks needed to get there.]
#import "../helpers/xref.typ": collab, suggestion
#import "../helpers/shared.typ": Dome
#import "../helpers/templates/milestones-matrix.typ": milestones-figure
= Outcomes <sec-outcomes>


*The instrument.* Our five-to-seven-year outcome is a single instrument — the DOME — realized in three human-scale forms and an animal-scale form that records the complete perception–action loop as one calibrated, uncertainty-tagged measurement and yields the same canonical record regardless of which sensors are present. DOME-L is the warehouse-scale flagship in Greater Boston; it drives each sub-instrument to its limit and is large enough to physically contain the smaller forms, which makes it the metrological reference for the entire network. DOME-S extends FreeMoCap's webcam capture into the disseminated lab- and classroom-scale form, and DOME-Mobile is the wearable form that carries the measurement onto natural terrain outside the lab. Because the instrument is defined by its measurement ontology rather than by any one sensor, a markerless-camera estimate and an inertial estimate describe the same kinematics and fuse into a single estimate better than either alone.

*The organizing benchmark - the retinal projection.* Every outcome below is a term in one uncertainty budget: reconstructing veridical retinal input — the world projected onto a moving agent's retina — to within 1° at the fovea while the agent fixates a point on the ground ahead. That target, and the current-art error sources it composes, are established in the Technology Landscape (@sec-technology-landscape; @fig-landscape-quantified).

// DEDUP resolved 2026-07-13: §2 now carries the brief landscape+build, §3 the mechanism+benchmarks. Remaining dedup applied below — the SOTA-numbers paragraph is cut (duplicates §2 "The eye") and "What the record unlocks" is trimmed of its §2-overlapping CV/RL framing.

*Body — A self-calibrating, semi-autonomous camera array.* On the motor half of the loop we deliver kinematics clean enough for inverse dynamics from markerless capture. The actuated, self-calibrating camera array places daisy-chained Power-over-Ethernet cameras on programmable mounts that stay metrically calibrated as one instrument while being re-aimed and re-focused from a single console, dissolving the practical bottleneck that tends to leave large motion capture rigs frozen in place due to the high cost of manual re-calibration. This is adaptive AI-based sensing in hardware: the algorithm reconfigures the physical optics to maximize observability, running autonomous experiments over camera geometry rather than settling for a hand-placed rig. Success is measured as post-reconfiguration calibration quality and the time from sub-volume selection to calibrated capture, against a fixed-calibration reprojection baseline. Camera-derived keypoints and IMU-derived segment orientaion estiamtes are fused then combines noisy-but-accurate outside-in estimates with precise-but-drifting inside-out estimates under explicit per-joint uncertainty, validated as joint-torque uncertainty against force-plate ground truth and muscle-force uncertainty against EMG-informed estimates.

The starting point is already quantified: FreeMoCap recovers joint centers to under 30 mm and sagittal joint angles to 2–4° RMSE against research-grade optical motion capture during treadmill gait, from a roughly \$120 six-webcam rig @cherian2026. The actuated array and camera–IMU fusion target the residual gap to inverse-dynamics-grade kinematics — per-joint uncertainty tight enough that derived joint torques and muscle forces carry meaningful error bars.


*Eye — the next generation of eye trackers.* Mobile eye tracking has been stalled for at least a decade. There are more powerful arrays of multispectral optical sensors on the back of a cell phone than there are in a modern eye tracker. We will build a new kind of eye tracker that measures degrees of freedom commercial trackers omit, with spatial and temporal accuracy beyond current expectation. We will design a dense array of multi-spectral sensors (including high-resolution *stereo RGB-IR sensors, ultra-high speed event cameras, 3d scanning LiDAR, and single-pixel MEMS imagers*) to reconstruct the eye to a level of spatiotemporal precision beyond the capacity of any existing system. We will keep our unit costs low by taking advantage of the economics of the commodity-imager curve, with the goal of creating a cost-collapse for next-gen eye tracking the way FreeMoCap did for motion capture. 

 The new eye tracker will resolves ocular torsion from iris texture — the degree of freedom that corrupts the curl of retinal optic flow and a standing research target @matthis2022. Realtime and post-hoc pipelines will produce microsaccade-scale resolution, and possibly unlock estimates of lens accommodation by tracking the dual-Purkinje image. Its benchmarks are sub-15-arcminute eye-in-head accuracy, ~1° torsion accuracy, and the composed 1° gaze-in-world target above.

// CUT applied 2026-07-13: the SOTA-numbers paragraph below is commented out (duplicates §2 "The eye"; §2 owns the landscape comparison).


// CUT (duplicates §2 "The eye"): For context, the best shipping mobile trackers report 0.6° (Tobii Pro Glasses 3), ~1° (AdHawk MindLink), and 1.3–1.8° (Pupil Labs Neon) gaze accuracy in the head frame — and none of them measure ocular torsion or lens accommodation at all (@fig-landscape-quantified). The sub-15-arcminute (0.25°) eye-in-head target is finer than any of these, and the torsion and accommodation channels are new measurements rather than incremental ones.


*World — the scene the agent acts in.* Reconstructing what the eye sees requires reconstructing the world it acts in, so a head-mounted world-scanner of stereo-RGB, structured-IR, and LiDAR produces per-frame RGB-D and, over longer horizons, a terrain mesh and a SLAM-corrected head trajectory that fixes inertial drift @muller2023. The same scanner package mounts on drone-swarm nodes that act as a mobile extension of the camera array, grounding DOME-Mobile's inside-out estimates outdoors where a fixed rig cannot reach, benchmarked as gaze and kinematic uncertainty against the DOME-L reference during co-recorded trials. Modular floor panels — each a force plate, terrain tile, or LED surface — and the ARGP perturbation platform close the world half of the loop by making the ground itself both sensor and controllable stimulus.


*One record across species.* Functionally equivalent instruments at collaborator labs yield the same canonical records as the human instrument. The animal-scale instrument already exists — the team's ferret and mouse builds integrate three-camera gaze, full-body kinematics, and world cameras in one calibrated system, with neural recordings being added now — and the human, mouse, and ferret builds are being brought to functional equivalence, extending to guinea fowl for musculoskeletal biomechanics with EMG #collab("MD") and marmoset for primate electrophysiology #collab("AH")/#collab("JY"). Success is cross-species measurement comparability under shared calibration and data-exchange protocols, so that a reconstructed `RetinalInput` or `RigidBody` denotes the same thing whether it came from a human, a ferret, or a marmoset.

// CONDENSED 2026-07-13 → green block below (trimmed the CV/RL framing that §2's close now carries; kept the mechanism unique to §3). Original:
// *What the record unlocks.* Because every channel is calibrated, synchronized, and uncertainty-traced within ona shared sensor-grounded ontology, a #Dome instrument generates its own training signal by back-projecting calibrated 3D reconstructions onto each camera's 2D view, and the resulting reprojection error fine-tunes pose estimators, measured as improvement on out-of-distribution movement — clinical gait, acrobatics, animal locomotion — rather than on a saturated benchmark: an instrument engineered for next-generation AI training pipelines. The record is natively reinforcement-learning-ready because a DOME export maps directly onto MuJoCo and Isaac Lab rigid-body models with uncertainty intact, so DOME-recorded corpora drive sim-to-real policy transfer and inverse-RL recovery of the control policies underlying observed behavior, testable back in DOME-L via ARGP perturbation.

*What the record unlocks.* Within one sensor-grounded ontology, the instrument generates its own training signal: back-projecting calibrated 3D reconstructions onto each camera's 2D view yields a reprojection-error signal that fine-tunes pose estimators on out-of-distribution movement rather than a saturated benchmark. And because a DOME export maps directly onto MuJoCo and Isaac Lab rigid-body models with uncertainty intact, DOME corpora drive sim-to-real transfer and inverse-RL recovery of the control policies underlying observed behavior — testable back in DOME-L via floor perturbation.


This self-improvement loop is already demonstrated at small scale: a generic pose estimator mistracks a transfemoral prosthesis by up to 152 mm at the ankle, but training a task-specific keypoint model on the instrument's own calibrated data drops that error to 8–14 mm @cherian2026. What was a one-off dissertation result becomes, in the DOME, a repeatable methodology capable of driving measurement beyond the capacities of the present landscape.



#milestones-figure