
//OFFICIAL INSTRUCTIONS

// [Proposing teams must describe one or more novel platform technologies that the proposed NSF X-Lab is uniquely suited to advance. Successful teams will have a clear vision statement of how their work will result in an end-state that reshapes an entire field of scientific inquiry or a sector of technology, and how their Mission is currently unmet by existing organizational structures and funding mechanisms.]

#import "../helpers/shared.typ": semibold, Dome, Domes, Dome-Mobile

= Mission

#let mission_statement = [
Develop and disseminate a new class of scientific instrument called a #semibold([Densely Overlapping Measurement Environment #smallcaps([(Dome)])]) that records the complete perception–action loop of a behaving agent as a single calibrated, uncertainty-tagged measurement, and build the autonomous organization dedicated to the measurement itself and form the boundary object that will align perceptual and motor neuroscience, musculoskeletal biomechanics, mobile robotics, and embodied AI into a single convergent science of sensorimotor control.]
 
#block(
  fill: rgb("#ddd"),
  radius: 1pt,
  stroke: (left: 2pt + gray),
  inset: (x: 0.5em, y: 0.5em),
)[#mission_statement]

==  A New Observable: The Sensorimotor Loop

 Every agent, living or engineered, must solve the same problem - sense a thin slice of available energy in the environment through a limited set of imperfect transducers and on its basis push its body against the world to propel itself towards its goal. Information flows in, forces flow out; the brain exists to yank the bones around.

 We can measure individual components of this loop with extraordinary precision progressing at the rate of our technology. Camera and IMU based motion capture can track the kinematics of the body, force plates measure the kinetic forces between the body and world. Outward facing cameras can measure the world, and inward facing cameras can track the eyes. For humans, EEG nets and surface EMG record course records of patterns of neural activity in the cortex and musculoskeletal system. In animal models, dense electrode arrays resolve the individual spikes of neurons and motor units.  

 And yet, despite the extradradoinary precision and progress along these individual threads of measurement, access to the coherent whole representing the shared observational context that each of these tools illuminates remains ellusive. Occasionally, a research team will reach accross disciplinary divides and stitch several threads together for heroic integrative studies, but the methods rarely escape the Methods sections of a small cluster of publications spanning roughly the timescale of a single PhD. 
 
 _[TODO - fold next two paragraphs into 'unmet need' and 'vision' sections below]_
  Each of these teams sought out to answer a question at the edge of their discipline and instead found themselves in the business of tool building. The build these tools because they know the answers to the questions that they seek lie in the output of the integrated tool that does not exist.  In an institution that rewards the plating of seeds over the tending of gardens, the long and laborious work of maintaining a novel complex instrument quickly overwhelms the capacity of an academic lab.  Eventually the nascent tool collapses under the weight of its own complexity, and what was meant to be a bridge between two domains of study instead fades into an evergrowing pile of academic abandonware.
  
  We need a new organization that exists outside of the siloed domains of the Academia that dedicates itself to the #smallcaps[measurement], the development and dissertation of world-class, convival tools and novel skillsets explore the landscape the capacity unlocks. That organization is the #semibold[FreeMoCap X-Lab] [FMC-X]. We have already changed the landscape human-focused research by bringing high-quality capture to over 15,000 researchers, clinicians, robotists, and animators across 152 countries. With the support of the NSF X-Labs program, we will extend our mission and change entire landscape of neuroscience, biomechanics and robotics.
  
==  A New Instrument: Building the #smallcaps[Dome] 


We define a #Dome as a densely instrumented region of real space engineered (at some aspirational extreme) to record every  possible measurable channel of the agent–environment interaction at once. It is the opposite of a space telescope, an empty volume of of lenses focused inward at the mysterious place where the body meets the world. 

 In practice, individual #Domes will comprise a partial subset of available instrumentation, selected based on use-case. However, criticall, #semibold([All #Domes produce the same output]) regardless of the component instruments - a metrologically-grounded record of semantically-coherent cannonical models *partially hydrated* by measurements from the available instruments [TODO - Define/invoke Sensor-Grounded Ontology thing here]. 
 
 A motion capture recording produces the same reconstructed `Head`  A mocap  `Skull` is assumed to have `Eye`s, reagardless of whether the subject was wearing an eye tracker to hydrate its Degrees of Freedom. Both a ferret and a human have a `Skull` wqhich maybe approxomated as the same `RigidBody` defining segments of the body of a humanoid robot [Collaborator - SH, CH, JH, GN, AS] _[TODO - This robot stuff is redundant to below, I think. need consolldation]_. The reconstructed `RetinalInput` derived from reconstructions of the `Body`, `Eye`, and `Environment` of a human participant running across a rocky field [Ref-Collab-MH/KB] are precisely the same data models as those derived from a `Marmoset` leaping from branch to branch with Neuropixel electrodes emdedded in its `SuperiorColliculus` leaping to platform [Ref-Collab-AH/JY], a `Ferret` chasing a fictive prey with a Miniscope viewer mounted over of its `PosteriorParietalCortex` [Ref-Collab-BS], and a `GuineaFowl` running across a pneumatically actuated platform with EMG-electrodes implanted in its `MedialGastrocnemius` [Ref-Collab-MD].

[TODO - reference specific work  building DOME-variants in flagship facility and fan-out of built-to-use variants to collaborator network. Mention targetting specific hardware based on practical and research-grounded needs - target Retinal input good enough to target ephys, needs build better eye tracker (dense sensor array for better eye data in general, and adding unmeasurable DoFs like torsion and accomdation for accurate retinal optic flow(CURL). Need world sensor to map environment, built into head-mounted world sensor array of eye tracker, later expanding to attach that scanner to drones. Auto-calibrating camera sensor array - break practicality plateus of large capture volumes, allow for autonomously driven experiments on ideal camera configureations, and ai-driven autonoumous collaborative experiments by intergrating drone-swarms in the scene (i.e. the drone swarms and camera arrays interact to test different capture configurations, training the drone-swarm control policies, all which preps for integrations into #Dome-Mobile later to ground inside-out sensors of IMU-suit and head-mounted world scanner) )]


// - [ALLUDE → §3: DOME-L warehouse specs, DOME-S build plans and FreeMoCap community metrics, DOME-Mobile sensor suite, eye-tracker DoF targets and validation, actuated camera array engineering, camera↔IMU fusion uncertainty budgets, force-plate floor panels, ARGPv3, drone swarm (later phase).]


== The New Capability


Because every channel is spatially calibrated, temporally synchronized, uncertainty-traced within a unified sensor-grounded ontology, #Dome records drop into modern reinforcement-learning and robotics stacks with minimal reshaping — giving embodied AI the real-world, uncertainty-bounded sensorimotor corpora that safe learning requires and that no current dataset provides.


Internally, each sensor stream is modelable agaist every other stream, both within recordings (modelling eye movements against head movent to model VOR) and across recordings (back-fill old datasets with models of Cyclotorsion after we build a new eye tracker that measures torsion). The data also provides internal automatic erorr signals - downstream estimates of body kinematics fused from IMU- and Camera-mocap can back project onto the the original cmaera images, defining a reprojection-error signal that can improve image pose-detection algorithms that are currently stuck on an increasingly long-in-the-tooth [TODO - synonym ] COCO dataset. 

The same #semibold[Sensor-Grounded Ontology] that [...allows us to align outputs for heterogoenous #Domes... ] makes the instrument legible to a human — explicit entities, explicit relationships, no assumed domain knowledge — makes its records natively legible to a machine: typed, grounded data over which a model can build reliable reasoning chains rather than guessing at unlabeled streams. This cleanliness is not a layer added on top; it is the property that lets a #Dome route its live streams and logs through a local model to assist novices, experts, and developers alike, and that lets published results tag back into one shared entity–relationship structure connecting them to the wider body of science.


// [→ §3: RigidBody/contact-force mapping, reprojection-error pipeline + Isaac Lab/MuJoCo RL integration, IRL methodology + validation, backfill/upfill statistical framework, AR perturbation hardware — LED floor panels, projection, VR.]
== Unmet Needs
[TODO - this section is redundant and overlapping with other stuff, and also way too verbose. Can be cut down later]
An instrument like this is unmet by existing organizational structures and funding mechanisms for reasons that are structural, not incidental. Building a scientific instrument is #semibold[a distinct craft, not a downstream application of domain expertise] — mastery of electrophysiology or biomechanics does not transfer to the engineering of a calibrated, maintainable measurement system, and because that difficulty is invisible from outside the craft, integrated measurement is repeatedly scoped as a student side-project, under-resourced, and abandoned when it proves to be a career of engineering rather than a semester of it. The deeper failure is not that these efforts collapse but that #semibold[even their successes do not compound]: a research result and a research instrument are different deliverables, and the second — a one-off tuned to a single rig, undocumented and unmaintained — rarely survives the trainee who built it. The field rewards the demonstration, not the durable artifact, and often cannot tell them apart, so proofs of concept are celebrated as finished tools and the unglamorous engineering that would turn one into an instrument others can trust is never done.

Where durable scientific instruments do exist, they were built by escaping this structure rather than succeeding within it — in institutes engineered for the purpose, or by rare leaders who treated maintenance as first-class against their own career incentives. That escape is the necessary condition. By Conway's Law, an enterprise of domain-named departments, journals, and grants can only produce domain-scoped instruments, reviewed by people who score work inside a single domain — never the long metrology that turns a proof of concept into shared infrastructure. A tool defined by a research domain partitions its users into specialists; a tool defined by a measurement unites everyone who needs that measurement and becomes a commons precisely because it imposes none of their goals. The FreeMoCap Foundation already ran this experiment: scoped to the measurement and refusing to claim a domain, it became a commons of over 15,000 users across 152 countries — but a commons cannot form around abandonware, so #semibold[the scoping argument and the engineering argument are the same argument].

The measurement therefore needs its own organization. The PI left a tenure-track position because the institution could not support this work, and founded the FreeMoCap Foundation as a 501(c)(3) whose primary output is open scientific instruments; the X-Lab's operating model follows directly — scope the deliverable to the instrument, hold full-time career engineers for years so the instrument accumulates the mastery that makes it trustworthy, and fan the science out to a standing network of collaborators who use the tools and feed insight back. This is not a critique offered from the sidelines. We know this failure mode because #semibold[we built the thing that does not exhibit it]: a working animal-scale instrument and a global user community, engineered to be installed, run, and extended by people who did not build it — exactly the standard the X-Labs model exists to fund, and one a university appointment cannot sustain.

// [→ §4, §5: PI expertise + departure from Northeastern; EI enterprise software; AC clinical validation; KM mobile DOME lineage; MN large-scale lab; JKL AI systems; RR org health + NSF grant mgmt; NR CEO ops; collaborator roster; governance (FMC-X within FMC-F, PI final say); autonomy at submission; congress/hackathon cadence; community grants; FreeMoCap scale receipts.]

// An instrument like

// [→ §4, §5: PI expertise + departure from Northeastern; EI enterprise software; AC clinical validation; KM mobile DOME lineage; MN large-scale lab; JKL AI systems; RR org health + NSF grant mgmt; NR CEO ops; collaborator roster; governance (FMC-X within FMC-F, PI final say); autonomy at submission; congress/hackathon cadence; community grants; FreeMoCap scale receipts.]
== The Vision
_[TODO - clean this Vision statement up and fold in some of the cleaner frameings from teh bot-text below]_
The vision of this proposal represents an grand acceleration of movement the FreeMoCap Project has fostered since 2021, and there is no upper limit to our ambition. The global spread of the FreeMoCap software shows that the world has a hunger for this kind of tool, and we intend to feed it. We will put a #Dome in every research lab, every classroom, every Physical Therapy clinic, animation studio,  and athletic facility. We will create field-deployable wearble #Dome-Mobile systems that provide lab-quality data of humans and animals in the remote wilderness. We will build them into the SCUBA systems of deep sea welders and into the EVA suits and HAB volumes of the ISS. Every country hospital and retirement home will have an AI-enabled, auto-calibrating, self-analyzing Gait and Posture facility that will have plain language conversations with patients about their own kinematic data. We will build #Domes into the sides of moutains to measure the aerodyanmics of hunting hawks, and onto the hulls of shipping boats to understand the mechanics of the dolphins that play in their wake. Every Zoo enclosure will become a 24/7 data stream, with animal tracking models jumpstarted through citizen science and then accelerated through auto-training backprojection pipelines. Previously disconnect specialized results on animal models and niche domains will connect through shared links in a Sensor Grounded Ontology, rather than being scattered across publications in specialized journals. The resulting web of scientific beliefs about neuroscience and biomechanics will trace backwards a shared ontology underpinning a unified science of natural behavior fed by every calibrated #Dome, be it a \$1,000,000 flagship facility or \$100 student kit.  so that ever reconstructed behavior embodies the same, eternal question - #smallcaps([Would you like to know more?])

// _[TODO - Clean up closing, tighten language. Idea is that each Dome's reconstructed data is connected to all of science through the SGO, so when a researcher or student is looking at it, they can, like, click on things and its like its asking them "would you like to know more" like, about the thing you are looking at or the world in general, ya know? ]_

// Platform measurement techniques behave this way. PCR was built to copy DNA; it went on to underwrite forensics, diagnostics, ancestry, and a pandemic response its inventors never imagined. Next-generation sequencing did not become foundational by being precious — it became foundational when it grew cheap and standardized enough that every lab could run it, and its applications followed the price collapse rather than preceding it. We are building the #Dome for a clear and present need; like those techniques, we expect the tool, once in the world's hands, to be turned to uses we could not have anticipated — and we are designing, from the first day, for that to be easy.

// == The Vision

// The vision of this proposal is a grand acceleration of a movement the FreeMoCap Project has fostered since 2021, and there is no upper limit to our ambition. Going from zero to more than 15,000 users across 152 countries in four years taught us that the world is hungry for this kind of tool, and we intend to feed it. We will put #Domes where the science and the need already are — research labs and classrooms, physical-therapy clinics and athletic facilities, animation studios, and the country hospitals and retirement homes where an auto-calibrating gait-and-posture station could hold a plain-language conversation with a patient about their own kinematics. We will build field-deployable #Dome-Mobile systems that bring lab-quality data to humans and animals in the open wilderness, into the EVA suits and habitat volumes of the ISS, and into zoo enclosures that could become around-the-clock behavioral archives.

// The deepest measure of success, though, is not where we put #Domes; it is what becomes possible once anyone can. Our strategy, carried over from FreeMoCap, is to build from the student's perspective — a tool that assumes no domain knowledge — precisely because a tool that does not gate on expertise becomes a boundary object that biomechanists, neuroscientists, roboticists, and clinicians can all stand on. Once the measurement is that easy, the deployments that matter most are the ones we would never think of: someone will mount a #Dome on a mountainside to measure a hunting hawk, or on a ship's hull to study the dolphins in its wake. We do not need to build those. We need to make them easy, and then get out of the way.

// The analogy we hold in mind is the internet. The internet did not change the world by adding new capacity to any individual computer; it created a protocol and a shared context in which computers could relate to one another. We are building the same kind of connective object for the science of behavior. However many new sensors we build along the way — and we build them — the point is the shared context: a Sensor-Grounded Ontology in which a \$100 student kit and a \$1,000,000 flagship facility produce the same kind of record, in which a result from a ferret lab and a result from a gait clinic are linked rather than scattered across incompatible journals, and in which every calibrated #Dome feeds one accumulating science of natural behavior. We intend to do for the study of behavior what the internet did for computing.

//re: cost collapse line
// The sensing is inexpensive by construction: full-body capture and the eye tracker are built from commodity, phone-grade imagers and ride the same falling cost curves as consumer electronics. The PI's Northeastern laboratory cost roughly \$250,000 to outfit, most of it motion capture; a #Dome targets equivalent-or-better measurement at a fraction of that, and a student kit at two orders of magnitude less — with the dominant cost in a flagship being the actuated ground plane, not the measurement itself.

// Because the X-Lab's research and development is grant-funded, the organization does not depend on hardware margin. It can therefore offer instruments at or near cost, reaching price points the commercial market is structurally unable to serve, and decoupling access to world-class measurement from any vendor's need to profit. Cost, here, is not a sales point; it is the variable that decides whether a measurement lives in a few elite laboratories or in every classroom, clinic, and field site that needs it — the same collapse by which sequencing and integrated circuits became platforms rather than instruments.